name: Automatisk bygg og deploy rule-dsl
on:
  push:
    branches:
      - main

jobs:
  automatisk-bygg:
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: write
      packages: write
      pull-requests: write
    name: Automatisk bygg og deploy av rule-dsl
    runs-on: ubuntu-latest
    steps:
      - name: Kanseller tidligere kjøringer
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
      - name: Sjekk ut kode
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Cache Maven pakker
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Deploy rule-dsl til github
        run: mvn -B --settings maven-settings.xml deploy -Dmaven.wagon.http.pool=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}